// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqrlEm6FcE4g6Niwndl-D7qZ09gDRjSO4',
    appId: '1:1016385821921:web:df77b8b8023ba5441d6ba0',
    messagingSenderId: '1016385821921',
    projectId: 'surveycam-1d727',
    authDomain: 'surveycam-1d727.firebaseapp.com',
    storageBucket: 'surveycam-1d727.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK0lUuPV2Bz2pJV5an0rjCnGkbeRGAnyQ',
    appId: '1:1016385821921:android:0c728a0b6b5985121d6ba0',
    messagingSenderId: '1016385821921',
    projectId: 'surveycam-1d727',
    storageBucket: 'surveycam-1d727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqx6pzsfwWxZrWd0wBKOBth_oJsUbHmOs',
    appId: '1:1016385821921:ios:2c9a73b406f580891d6ba0',
    messagingSenderId: '1016385821921',
    projectId: 'surveycam-1d727',
    storageBucket: 'surveycam-1d727.appspot.com',
    iosBundleId: 'com.example.surveyCam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqx6pzsfwWxZrWd0wBKOBth_oJsUbHmOs',
    appId: '1:1016385821921:ios:27d74696ba4c6b771d6ba0',
    messagingSenderId: '1016385821921',
    projectId: 'surveycam-1d727',
    storageBucket: 'surveycam-1d727.appspot.com',
    iosBundleId: 'com.example.surveyCam.RunnerTests',
  );
}
